### ISSUE TITLE
Package not published?

### ISSUE THREAD

**Issue by adriantoine** [threadheap/reselect-weakmap-memoize#1]
Hi!

I have tried to install this package but I get this error:
```
$ yarn add relesect-weakmap-memoize
yarn add v1.3.2
[1/4] 🔍  Resolving packages...
error Couldn't find package "relesect-weakmap-memoize" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

and it doesn't seem to be in the npm registry: https://www.npmjs.com/package/relesect-weakmap-memoize.

**Comment by pavelvlasov** [comment]
Hi! Thanks for heads up. It's actually published, but there's a typo in readme. This is right url https://www.npmjs.com/package/reselect-weakmap-memoize
